default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: galileugalilei
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bootcamp9_development

test:
  <<: *default
  database: bootcamp9_test
